INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (1,'AMY',100,'Fmale','0982100947','瑞光路62號','28',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (2,'TOMMY',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (3,'Barry',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (4,'Bartley',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (5,'Beau',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (6,'Egbert',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (7,'Eldred',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (8,'Edwiin',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (9,'Mortimer',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (10,'Morton',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (11,'Murray',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (12,'Myron',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);
INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (13,'Prescott',101,'Male','0982405940','陽光街22號','18',sysdate,sysdate);

INSERT INTO DEPT_DATA (DEPT_ID , DEPT_NAME) VALUES (100 , 'A部門' );
INSERT INTO DEPT_DATA (DEPT_ID , DEPT_NAME) VALUES (101 , 'B部門' );
