INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (1,'AMY','A01','Fmale','0982100947','瑞光路62號','28',sysdate,sysdate);

INSERT INTO MEMBER (EMP_NO  ,NAME, DEPT_ID, SEX , PHONE_NUMBER , ADDRESS , AGE, CREATE_DATE , MOD_DATE )
VALUES (2,'TOMMY','A02','Male','0982405940','陽光街22號','18',sysdate,sysdate);